# Generated by Django 5.2.4 on 2025-07-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prestamo',
            unique_together=set(),
        ),
    ]
